# checks for GitHub Actions updates
version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    
    # trigger at 2:25 PM EST every day
    schedule:
      
      interval: "cron"
      cronjob: "25 14 * * *"
      timezone: "America/New_York"
