---
# custom image details
name: ublue-test
description: Custom Universal Blue test image by BlastPKMN

# base image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# module configuration, executed in order
modules:
  
  - type: script
    
    # run scripts
    scripts:
    
      - kernel-cachyos.sh

  - type: dnf  
   
    # install packages    
    install:

      packages:
      
        - fastfetch
        - fish
        
    # remove packages
    remove:
      
      packages:

        - ark
        - fcitx5
        - filelight
        - firefox
        - firefox-langpacks
        - firewall-config
        - htop
        - kate
        - kde-connect
        - kde-partitionmanager
        - kcharselect
        - kdebugsettings
        - kfind
        - khelpcenter
        - kinfocenter
        - kjournald
        - krfb
        - kwalletmanager5
        - kwrite
        - nvtop
        - plasma-discover
        - plasma-drkonqi
        - plasma-welcome
        
  # this sets up the proper policy and signing files for signed images to work fully
  - type: signing
