# build details
name: bluebuild

on:
  
  schedule:
    
    # trigger build at 2:35 PM EST daily
    - cron: "35 14 * * *"
      timezone: "America/New_York"
  
  push:
    
    paths-ignore:
      
      # do not rebuild if only documentation has changed
      - "**.md"

  pull_request:
  
  # allow manually triggering builds
  workflow_dispatch:

concurrency:
  
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  
  # job to build custom image
  bluebuild:
    
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      
      contents: read
      packages: write
      id-token: write
    
    strategy:
      
      # stop GitHub from cancelling all matrix builds if one fails
      fail-fast: false
      
      matrix:
        
        # add your recipes here
        recipe:
          
          - recipe.yml
    
    steps:
      
      # the build is fully handled by the reusable GitHub action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.12.0
        with:
          
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # rechunk the image, allowing for smaller images and smaller updates
          build_chunked_oci: true

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true
